### ISSUE TITLE
create featurizerMPI and integrate with msmbuilder

### ISSUE THREAD

**Issue by cxhernandez** [cxhernandez/msmbuilderMPITools#5]
Ideally would be based on [featurizeLP-MPI](https://github.com/cxhernandez/msmbuilderMPITools/blob/master/featurizeLP-MPI) (which has write-locking now), but would allow for custom curation of msmbuilder featurizations. 

This might be best done with a `.yaml` configuration file, like osprey:

``` yaml
featurizers:
    [('dihedrals', DihedralFeaturizer,
      'rmsd', RMSDFeaturizer)]

options:
  dihedrals__types: ['phi', 'psi', 'chi1', 'chi2']
  rmsd__atom_indices: backbone

trajectory_loader:
  params:
    trajectories: ./fs_peptide/trajectory-*.xtc
    topology: ./fs_peptide/fs-peptide.pdb
    stride: 100

output: ./features.h5
```

cc @mpharrigan @msultan
